In [22]:
import geopandas as gpd
import pandas as pd

In [23]:
grid = gpd.read_file('grid_1204.geojson')

In [24]:
grid .head()

,TARGET_FID,Id,Shape_Leng,Shape_Area,GeoID,grid_id,imp_percent,imp_score,flood_score,green_score,greenview_index,storwater_managed,treecountestimate,overall_score,geometry
0,1,0,2530.758569,385934.045109,1.0,1,43.007936,4,0,0.0,0.000000,0,0,1.333333,"POLYGON ((-74.05343 40.76242, -74.05548 40.762..."
1,2,0,2655.536428,444097.228757,2.0,2,54.205350,3,1,0.0,0.000000,0,0,1.333333,"POLYGON ((-74.09057 40.73430, -74.09262 40.734..."
2,3,0,2721.468967,450465.444325,3.0,3,54.068938,3,1,0.0,0.000000,0,0,1.333333,"POLYGON ((-74.10300 40.71478, -74.10505 40.714..."
3,4,0,2721.468310,450465.184524,4.0,4,79.203148,2,1,0.0,17.946235,156800,196,1.000000,"POLYGON ((-74.07227 40.70597, -74.07433 40.705..."
4,5,0,2721.468310,450465.184524,5.0,5,94.985259,0,1,0.0,0.000000,0,0,0.333333,"POLYGON ((-74.06193 40.71898, -74.06398 40.718..."

In [25]:
grid = grid[grid.columns.tolist()[:6]+['geometry']]

In [26]:
grid.head()

,TARGET_FID,Id,Shape_Leng,Shape_Area,GeoID,grid_id,geometry
0,1,0,2530.758569,385934.045109,1.0,1,"POLYGON ((-74.05343 40.76242, -74.05548 40.762..."
1,2,0,2655.536428,444097.228757,2.0,2,"POLYGON ((-74.09057 40.73430, -74.09262 40.734..."
2,3,0,2721.468967,450465.444325,3.0,3,"POLYGON ((-74.10300 40.71478, -74.10505 40.714..."
3,4,0,2721.468310,450465.184524,4.0,4,"POLYGON ((-74.07227 40.70597, -74.07433 40.705..."
4,5,0,2721.468310,450465.184524,5.0,5,"POLYGON ((-74.06193 40.71898, -74.06398 40.718..."

In [27]:
final_scores = pd.read_csv('jc_grid_Scores_final.csv')

In [28]:
grid = grid.merge(final_scores,left_on = 'grid_id', right_on='grid_id')

In [29]:
grid = gpd.GeoDataFrame(grid)

In [30]:
grid.to_file('grid_final.geojson',driver='GeoJSON')